"""fix_audio_chat_created_at_field

Revision ID: 8686903bc931
Revises: c6dce3375577
Create Date: 2025-07-24 12:09:44.093977

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8686903bc931'
down_revision: Union[str, None] = 'c6dce3375577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_index(op.f('ix_userinfo_username'), table_name='userinfo')
    op.drop_table('userinfo')
    op.add_column('structured_notes', sa.Column('chat_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('structured_notes_chat_id_fkey'), 'structured_notes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('structured_notes_chat_id_fkey'), 'structured_notes', 'chat', ['chat_id'], ['id'])
    op.drop_column('structured_notes', 'chat_type')
    op.create_table('userinfo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('total_study_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('study_streak_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_study_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('userinfo_pkey')),
    sa.UniqueConstraint('email', name=op.f('userinfo_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_userinfo_username'), 'userinfo', ['username'], unique=True)
    op.create_table('videos',
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('videos_pkey'))
    )
    # ### end Alembic commands ###
