"""fix_audio_chat_created_at_field

Revision ID: c11c5144349f
Revises: af9299f121b7
Create Date: 2025-07-23 12:31:37.926669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c11c5144349f'
down_revision: Union[str, None] = 'af9299f121b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_index(op.f('ix_userinfo_username'), table_name='userinfo')
    op.drop_table('userinfo')
    # Add created_at column as nullable first
    op.add_column('audio_chat', sa.Column('created_at', sa.DateTime(), nullable=True))
    # Update existing records with current timestamp
    op.execute("UPDATE audio_chat SET created_at = NOW() WHERE created_at IS NULL")
    # Make the column NOT NULL
    op.alter_column('audio_chat', 'created_at', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the created_at column
    op.drop_column('audio_chat', 'created_at')
    op.create_table('userinfo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('total_study_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('study_streak_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_study_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('userinfo_pkey')),
    sa.UniqueConstraint('email', name=op.f('userinfo_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_userinfo_username'), 'userinfo', ['username'], unique=True)
    op.create_table('videos',
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('videos_pkey'))
    )
    # ### end Alembic commands ###
