name: Deploy to VM with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Rsync to VM
        run: |
          rsync -avz --exclude='.git*' --exclude='node_modules' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/learnin/LearnIn

      - name: Rebuild and restart Docker
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /home/learnin/LearnIn
            docker compose down
            docker compose up --build -d
          EOF
